version: "3"
services:
  centos7tommath:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
      dockerfile: Dockerfile.math
  centos7tomcrypt:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
      dockerfile: Dockerfile.crypt

volumes:
  rpm7:
    name: rpm7
